### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by chiaramistro**
Proposal for favicon

### CODE REVIEW

**Comment by sbimochan** [comment]
You also need to add it on index.html with favicon.ico
Do think about visual for logo since it will be displayed in small size in tab.

**Comment by chiaramistro** [comment]
> You also need to add it on index.html with favicon.ico
> Do think about visual for logo since it will be displayed in small size in tab.

I added it to the html. Let me know what you think about the icon itself (for example, if you like the colors)

**Comment by sbimochan** [comment]
> > You also need to add it on index.html with favicon.ico
> > Do think about visual for logo since it will be displayed in small size in tab.
> 
> I added it to the html. Let me know what you think about the icon itself (for example, if you like the colors)

You haven't. Maybe you forgot to push commit?

**Comment by chiaramistro** [comment]
> > > You also need to add it on index.html with favicon.ico
> > > Do think about visual for logo since it will be displayed in small size in tab.
> > 
> > 
> > I added it to the html. Let me know what you think about the icon itself (for example, if you like the colors)
> 
> You haven't. Maybe you forgot to push commit?

I committed before and I did it again. However, I don't unterstand if you are able to see it already in your readme file...

**Comment by sbimochan** [comment]
Sorry, closing it because I found a better favicon. Please feel free to try another issues. Happy hacking :)

**Pull request closed without merging**
